POST http://animo10.brazilsouth.cloudapp.azure.com:8080/aula
Content-Type: application/javascript

{
  "disciplina": {
    "nome": "Desenvolvimento Mobile",
    "_id": "5bb4f2ef-ffe6-47c2-8dc3-ee6cdd17be38",
    "_rev": "1-b3bb5f9454c4448eb0ad336b69bd85ec"
  },
  "professor":   {
    "nome": "Nelson",
    "foto": "teste",
    "_id": "c75980c8-3b1d-487e-a267-525dc3dc09a5",
    "_rev": "1-ec6523fcf39c4007868740f621b96835"
  },
  "data": "2018-03-10T03:00:00.000Z"
}

###
GET http://animo10.brazilsouth.cloudapp.azure.com:8080/professor











